from .agent_prompts import (
    PRODUCT_ANALYST_ROLE,
    PRODUCT_ANALYST_GOAL,
    PRODUCT_ANALYST_BACKSTORY,
    SOLUTION_DESIGNER_ROLE,
    SOLUTION_DESIGNER_GOAL,
    SOLUTION_DESIGNER_BACKSTORY,
    TECHNICAL_ARCHITECT_ROLE,
    TECHNICAL_ARCHITECT_GOAL,
    TECHNICAL_ARCHITECT_BACKSTORY,
    CRITIC_SYNTHESIZER_ROLE,
    CRITIC_SYNTHESIZER_GOAL,
    CRITIC_SYNTHESIZER_BACKSTORY,
    build_product_analyst_prompt,
    build_solution_designer_prompt,
    build_technical_architect_prompt,
    build_critic_synthesizer_prompt,
)

__all__ = [
    "PRODUCT_ANALYST_ROLE",
    "PRODUCT_ANALYST_GOAL",
    "PRODUCT_ANALYST_BACKSTORY",
    "SOLUTION_DESIGNER_ROLE",
    "SOLUTION_DESIGNER_GOAL",
    "SOLUTION_DESIGNER_BACKSTORY",
    "TECHNICAL_ARCHITECT_ROLE",
    "TECHNICAL_ARCHITECT_GOAL",
    "TECHNICAL_ARCHITECT_BACKSTORY",
    "CRITIC_SYNTHESIZER_ROLE",
    "CRITIC_SYNTHESIZER_GOAL",
    "CRITIC_SYNTHESIZER_BACKSTORY",
    "build_product_analyst_prompt",
    "build_solution_designer_prompt",
    "build_technical_architect_prompt",
    "build_critic_synthesizer_prompt",
]
